[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "opendg"
version = "0.1.0"
description = "An Open Library for Temporal Graph Learning"
readme = "README.rst"
requires-python = ">=3.9"
authors = [
    {name="Shenyang Huang", email="shenyang.huang@mail.mcgill.ca"},
    {name="Jacob Chmura", email="jacobpaul.chmura@gmail.com"},
]
dependencies = []
